# Generated by Django 3.0.6 on 2020-06-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20200615_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='资源名', max_length=20)),
                ('resource_type', models.CharField(max_length=1)),
                ('resource_key', models.CharField(help_text='资源类型', max_length=50)),
                ('resource_score', models.CharField(help_text='资源分', max_length=10)),
                ('resource_text', models.CharField(help_text='资源描述', max_length=200)),
                ('resource_user', models.CharField(help_text='上传者', max_length=20)),
                ('up_time', models.DateTimeField(auto_now=True)),
                ('ext', models.CharField(help_text='文件后缀', max_length=10)),
                ('size', models.CharField(help_text='文件大小', max_length=10)),
                ('uer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='user.User')),
            ],
            options={
                'db_table': 'resource',
            },
        ),
    ]
