# Generated by Django 3.0.6 on 2020-06-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(max_length=10),
        ),
    ]
