# Generated by Django 3.0.6 on 2020-06-16 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200615_1503'),
        ('resource', '0003_auto_20200616_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='uer',
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='user.User'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ext',
            field=models.CharField(blank=True, help_text='文件后缀', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_user',
            field=models.CharField(blank=True, help_text='上传者', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='size',
            field=models.CharField(blank=True, help_text='文件大小', max_length=10),
        ),
    ]
