# Generated by Django 3.0.6 on 2020-06-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_resource_download_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_user_id', models.CharField(help_text='评论用户id', max_length=10)),
                ('com_time', models.DateTimeField(auto_now=True)),
                ('com_text', models.CharField(help_text='评论内容', max_length=200)),
                ('star', models.CharField(help_text='星级', max_length=1)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='resource.Resource')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
