# Generated by Django 3.0.6 on 2020-06-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
