# Generated by Django 3.0.6 on 2020-06-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_auto_20200617_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coll_user', models.CharField(help_text='收藏用户id', max_length=10)),
                ('coll_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect', to='resource.Resource')),
            ],
            options={
                'db_table': 'collect',
            },
        ),
    ]
