# Generated by Django 3.0.6 on 2020-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0010_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='coll_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
